### ISSUE TITLE
Set Up hybris B2C accelerator using HSQL db

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/alex_repo#1]
As a **Developer**
I want to have local hybris environment with B2C accelerator (on HSQL db), 
So that I could work with hybris platform on my local machine

**AC:**
1) hybris installed
2) hybris built
3) hybris initialized
4) checkout process could be successfully done and you finally have an order as a result

_Tips:_
How to install -- https://wiki.hybris.com/display/tr52/Telco+Accelerator
Development environment setup example -- https://kb.epam.com/display/ECOMCC/Dev-Environment+Setup+for+iPromoTarget+project
EPAM how-to -- https://kb.epam.com/display/ECOMCC/Platform+Installation+Instructions

**Comment by Skrakan** [comment]
![image](https://user-images.githubusercontent.com/17614859/29366766-9a710436-82a3-11e7-9dbf-a545df6fb131.png)
