### ISSUE TITLE
Generate custom accelerator extensions

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/alex_repo#2]
As a **Developer**
I need to have custom **B2C** extensions, 
So that I could add custom changes to this extension

**AC:**
1) Next extensions should be created:

> trainingcockpits
> trainingcore
> trainingfacades
> trainingfulfilmentprocess
> traininginitialdata
> trainingstorefront
> trainingtest

2) package should be **com.epam.training**

_Tips:_
https://wiki.hybris.com/display/release5/Creating+a+New+Extension
https://wiki.hybris.com/display/accdoc/Customizing+the+Accelerator+with+extgen+and+modulegen

**Comment by Skrakan** [comment]
![image](https://user-images.githubusercontent.com/17614859/29370161-410e2be4-82ad-11e7-83c0-8e8d3c1e6b77.png)
![image](https://user-images.githubusercontent.com/17614859/29370179-4b045484-82ad-11e7-9d29-f20cdf185e62.png)

**Comment by Skrakan** [comment]
![image](https://user-images.githubusercontent.com/17614859/29370444-0526eb38-82ae-11e7-90c8-f938b12787be.png)
